version: '3.8'

name: small_qu

services:
  frontend:
    image: small_qu:front
    # container_name: small-front
    # hostname: smallQ-front
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./shared:/app/shared
    environment:
      PORT: 4000
    networks:
      - overlay
    links:
      - backend

  backend:
    image: small_qu:back
    # container_name: smallQ-back
    # hostname: smallQ-back

    build:
      context: .
      dockerfile: back/main_sever/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./shared:/app/shared
    networks:
      - overlay

networks:
  overlay:
    driver: bridge
    name: overlay

