name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name : clone current branch
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        working-directory: ./hoodone/back/main-sever # Change this to the correct folder
        run: npm ci
      - name: Run Prettier
        working-directory : ./hoodone/back/main-sever
        run: npm run format
